query humm($limit: Int) {
  Article(limit: $limit, filter: {type: {_eq: "food"}}) {
    slug
    video
    user_updated {
      first_name
      last_name
    }
    date_created_func {
      day
      month
      year
    }
    translations {
      title
      content
      cover {
        id
      }
    }
    category {
      slug
      translations {
        title
        cover {
          id
        }
      }
    }
  }
}
